import { Bebas_Neue, Inter_Tight } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import { ViewTransitions } from "next-view-transitions";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${bebasNeue.variable} ${interTight.variable} antialiased`}
        >
          <Nav />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
